Footer
CodersCamp2020-HK/CodersCamp2020.Project.FullStack-Node-React pull request #165
Opened 2021-03-20 14:14 UTC by Haivex

Ostylowana stopka

2021-03-20 14:24 UTC, KrolMateusz requested changes

2021-03-20 14:24 UTC, KrolMateusz commented on src/presentation/web/src/themes/theme.tsx
> +
Można usunąć

2021-03-20 14:35 UTC, Haivex commented on src/presentation/web/src/themes/theme.tsx
> +
No tak, zapomniałem

2021-03-20 14:40 UTC, Haivex commented on src/presentation/web/src/themes/theme.tsx
> +
Poprawione

2021-03-20 14:51 UTC, KrolMateusz approved these changes, later dismissed

2021-03-21 14:48 UTC, bat098 approved these changes, later dismissed

2021-03-21 14:48 UTC, bat098 commented on src/presentation/web/src/components/Footer/Footer.module.css
> +    position: absolute;
Dodanie position: absolute; spowoduję, że główny content strony zostanie przesłonięty. Bez tej właściwości stopka ustawi się sama w odpowienim miejscu, jeśli znajda się pozostałe elementy na stronie.

2021-03-21 16:28 UTC, KrolMateusz approved these changes

2021-03-21 16:29 UTC, bat098 approved these changes

2021-03-21 16:29 UTC, merged