React activation link
CodersCamp2020-HK/CodersCamp2020.Project.FullStack-Node-React pull request #175
Opened 2021-03-22 12:47 UTC by Haivex

Komponent z informacją o wysłaniu linku

2021-03-23 12:17 UTC, KrolMateusz requested changes

2021-03-23 12:17 UTC, KrolMateusz commented on src/presentation/web/src/components/activationSent/ActivationSent.tsx
> +                    Mail z linkiem aktywacyjnym powienien zostać dostarczony w
Literówka

2021-03-23 16:01 UTC, KrolMateusz approved these changes, later dismissed

2021-03-23 18:11 UTC, bat098 submitted a review, later dismissed

2021-03-23 19:36 UTC, KrolMateusz submitted a review, later dismissed

2021-03-26 11:31 UTC, KrolMateusz submitted a review, later dismissed

2021-03-27 12:40 UTC, bat098 approved these changes, later dismissed

2021-03-27 19:09 UTC, KrolMateusz submitted a review, later dismissed

2021-03-28 16:35 UTC, bat098 submitted a review, later dismissed

2021-03-28 20:16 UTC, bat098 approved these changes

2021-03-28 20:20 UTC, dudeek approved these changes

2021-03-28 20:24 UTC, merged