Remove animal
CodersCamp2020-HK/CodersCamp2020.Project.FullStack-Node-React pull request #43
Opened 2021-02-27 14:03 UTC by bat098

- możliwość usuwania zwierzęcia z bazy danych
- dodanie opisu do do delete endpoint
- dodanie opisu entity Animal

2021-03-01 12:16 UTC, KrolMateusz requested changes

2021-03-01 12:16 UTC, KrolMateusz commented on src/presentation/rest/AnimalsController.ts
> +     */
Można dodać walidację `@isInt` dla parametru `animalId`

2021-03-01 12:16 UTC, KrolMateusz commented on src/application/AnimalsService.ts
> +        if (!animal) throw new Error(`Animal with id: ${id} does not exist`);
Możesz dodać error handling wykorzystując klasę `ApiError`. Wtedy w 'AnimalService.ts` rzucasz wyjątek `ApiError` oraz dodajesz response w kontrolerze.
Wyjątek: 
```ts
throw new ApiError('Not Found', 404, `Animal with id: ${id} not found!`);
```
Kontroler:
```ts
@Response<ApiError>(404, 'Not Found')
```

2021-03-02 14:25 UTC, KrolMateusz approved these changes, later dismissed

2021-03-03 21:10 UTC, Haivex approved these changes, later dismissed

2021-03-03 22:06 UTC, Haivex approved these changes

2021-03-03 22:07 UTC, dudeek approved these changes

2021-03-03 22:09 UTC, merged