Api error handler
CodersCamp2020-HK/CodersCamp2020.Project.FullStack-Node-React pull request #44
Opened 2021-02-27 18:56 UTC by Haivex

2021-02-27 22:17 UTC, htk4 requested changes

2021-02-27 22:17 UTC, htk4 commented on src/presentation/rest/Api.ts
> +import errorHandler from 'api-error-handler';
Na pewno potrzebujemy takiej [paczki](https://github.com/expressjs/api-error-handler/blob/master/index.js)? Nie lepiej napisać samemu? Później będziemy mogli dostosować do naszych potrzeb. Co myślisz @KrolMateusz?

2021-02-28 12:32 UTC, KrolMateusz commented on src/presentation/rest/Api.ts
> +import errorHandler from 'api-error-handler';
Zupełnie się z tobą zgadzam. Najlepiej będzie jak napiszemy własny middleware do obsługi błędów

2021-02-28 15:58 UTC, Haivex commented on src/presentation/rest/Api.ts
> +import errorHandler from 'api-error-handler';
Zmienione :)

2021-02-28 16:10 UTC, KrolMateusz approved these changes, later dismissed

2021-02-28 18:10 UTC, KrolMateusz approved these changes

2021-02-28 19:35 UTC, htk4 approved these changes

2021-02-28 20:31 UTC, merged