DataBaseEntities
CodersCamp2020-HK/CodersCamp2020.Project.FullStack-Node-React pull request #67
Opened 2021-03-07 17:13 UTC by blackrabbit2

2021-03-10 16:22 UTC, bat098 submitted a review, later dismissed

2021-03-10 21:16 UTC, htk4 requested changes
Na tyle, na ile dałem radę, to zaznaczyłem poprawki. Resztę błędów wyłapie się na produkcji 😉.

2021-03-10 21:16 UTC, hkawalek commented on src/IocContainerSetup.ts
> +import Questionnaire from '@infrastructure/postgres/Form';
Wybierz jedno  `Questionnaire` czy `Form`

2021-03-10 21:16 UTC, hkawalek commented on src/application/UsersService.ts
> +        const role = organizationUser === undefined ? UserType.NORMAL : organizationUser.role;
A co w przypadku, gdy użytkownik pełni różne `role` w kilku organizacjach? Chociaż, jeżeli założymy, że mamy tylko jedną organizację to powinno być ok?

2021-03-10 21:16 UTC, hkawalek commented on src/infrastructure/postgres/AdoptionStep.ts
> +@Entity('AdoptionSteps')
`AdoptionStep` czy `AdoptionSteps` ? Wybierz jedno tylko wszędzie konsekwentnie.

2021-03-10 21:16 UTC, hkawalek commented on src/infrastructure/postgres/Animal.ts
>  }
`animalsHandlers`?

2021-03-10 21:16 UTC, hkawalek commented on src/infrastructure/postgres/FormAnimalSubmission.ts
> +export default class FormAnimalSubmission {
Co z datą złożenia/rozpatrzenia ?

2021-03-10 21:16 UTC, hkawalek commented on src/infrastructure/postgres/AdoptionStep.ts
> +    name!: string;
Czy przypadkiem wszystkie pola które mogą być `nullable`, nie powinny mieć typ `name?: string` ?

2021-03-10 21:16 UTC, hkawalek commented on src/infrastructure/postgres/FormVolunteerSubmission.ts
> +export default class FormVolunteerSubmission {
To samo co w przypadku `FormAnimalSubmission` data złożenia/rozpatrzenia ?

2021-03-10 21:16 UTC, hkawalek commented on src/infrastructure/postgres/Goal.ts
> +export default class Goal {
Przydałyby się pola opisu zbiórki, albo nazwa zbiórki.

2021-03-10 21:16 UTC, hkawalek commented on src/infrastructure/postgres/Goal.ts
> +    gaolDonation!: GoalDonation;
typo

2021-03-10 21:16 UTC, hkawalek commented on src/infrastructure/postgres/AnimalDonation.ts
> +    @OneToMany(() => User, (user) => user.animalDonation, { cascade: true })
Powinno być `ManyToOne`

2021-03-10 21:16 UTC, hkawalek commented on src/infrastructure/postgres/AnimalDonation.ts
> +    @OneToMany(() => Animal, (animal) => animal.animalDonation, { cascade: true })
Tak samo `ManyToOne`

2021-03-10 21:16 UTC, hkawalek commented on src/infrastructure/postgres/Animal.ts
> +    @ManyToOne(() => AnimalDonation, (animalDonation) => animalDonation.animals)
OneToMany

2021-03-10 21:16 UTC, hkawalek commented on src/infrastructure/postgres/Animal.ts
> +    @ManyToOne(() => Goal, (goal) => goal.animals)
OneToMany

2021-03-10 21:16 UTC, hkawalek commented on src/infrastructure/postgres/Goal.ts
> +    @OneToMany(() => Animal, (animal) => animal.animalDonation, { cascade: true })
ManyToOne

2021-03-10 21:16 UTC, hkawalek commented on src/infrastructure/postgres/Goal.ts
> +    @OneToMany(() => Organization, (organization) => organization.goal, { cascade: true })
ManyToOne

2021-03-10 21:16 UTC, hkawalek commented on src/infrastructure/postgres/GoalDonation.ts
> +    @OneToMany(() => User, (user) => user.goalDonation, { cascade: true })
ManyToOne

2021-03-10 21:16 UTC, hkawalek commented on src/infrastructure/postgres/GoalDonation.ts
> +    @OneToMany(() => Goal, (goal) => goal.gaolDonation, { cascade: true })
ManyToOne

2021-03-10 21:16 UTC, hkawalek commented on src/infrastructure/postgres/Organization.ts
> +    @ManyToOne(() => Goal, (goal) => goal.organizations)
OneToMany

2021-03-10 21:16 UTC, hkawalek commented on src/infrastructure/postgres/OrganizationDonation.ts
> +    @OneToMany(() => User, (user) => user.organizationDonation, { cascade: true })
ManyToOne

2021-03-10 21:16 UTC, hkawalek commented on src/infrastructure/postgres/Organization.ts
> +    @ManyToOne(() => OrganizationDonation, (organizationDonation) => organizationDonation.organizations, {
OneToMany

2021-03-10 21:16 UTC, hkawalek commented on src/infrastructure/postgres/OrganizationDonation.ts
> +    @OneToMany(() => Organization, (organization) => organization.organizationDonation, { cascade: true })
ManyToOne

2021-03-10 21:16 UTC, hkawalek commented on src/infrastructure/postgres/OrganizationUser.ts
> +    @ManyToOne(() => Organization, (organization) => organization.organizationUsers)
`{ primary: true, nullable: false }`?

2021-03-10 21:16 UTC, hkawalek commented on src/infrastructure/postgres/Specie.ts
> +export default class Specie {
Nie powinno mieć relacji do `Animal` ?

2021-03-10 21:16 UTC, hkawalek commented on src/infrastructure/postgres/Specie.ts
> +    specie!: string;
unique?

2021-03-10 21:16 UTC, hkawalek commented on src/infrastructure/postgres/User.ts
> +    @ManyToOne(() => AnimalDonation, (animalDonation) => animalDonation.users, { cascade: true })
OneToMany

2021-03-10 21:16 UTC, hkawalek commented on src/infrastructure/postgres/User.ts
> +    @ManyToOne(() => OrganizationDonation, (organizationDonation) => organizationDonation.users, { cascade: true })
OneToMany

2021-03-10 21:16 UTC, hkawalek commented on src/infrastructure/postgres/User.ts
> +    @ManyToOne(() => GoalDonation, (goalDonation) => goalDonation.users, { cascade: true })
OneToMany

2021-03-10 21:16 UTC, hkawalek commented on src/infrastructure/postgres/VolunteerHireStep.ts
> +    number!: number;
`{ primary: true, nullable: false }`

2021-03-11 10:04 UTC, KrolMateusz commented on src/infrastructure/postgres/AdoptionStep.ts
> +@Entity('AdoptionSteps')
Tabele w bazie danych są w liczbie mnogiej, nazwy klas oraz nazwy plików są w liczbie pojedynczej. To jest bez znaczenia, bo repozytorium jest tworzone do klasy

2021-03-11 11:32 UTC, KrolMateusz approved these changes, later dismissed

2021-03-11 12:59 UTC, KrolMateusz approved these changes, later dismissed

2021-03-11 16:24 UTC, KrolMateusz submitted a review, later dismissed

2021-03-11 16:54 UTC, KrolMateusz submitted a review, later dismissed

2021-03-11 16:55 UTC, bat098 submitted a review, later dismissed

2021-03-11 16:58 UTC, KrolMateusz approved these changes

2021-03-11 17:11 UTC, htk4 approved these changes

2021-03-11 17:11 UTC, dudeek approved these changes

2021-03-11 17:12 UTC, merged