Change form status
CodersCamp2020-HK/CodersCamp2020.Project.FullStack-Node-React pull request #94
Opened 2021-03-12 19:11 UTC by Haivex

Zmiana statusu dla formularzy o adopcje i wolontariusza

2021-03-12 19:22 UTC, bat098 submitted a review, later dismissed

2021-03-12 19:33 UTC, KrolMateusz requested changes

2021-03-12 19:33 UTC, KrolMateusz commented on src/application/FormService.ts
> +    }
Można przenieść do pliku `AnimalSubmissionsService.ts`, tak jak masz w pr #93

2021-03-12 19:33 UTC, KrolMateusz commented on src/presentation/rest/FormController.ts
> +    }
Można przenieść do pliku `AnimalSubmissionsController.ts`, tak jak masz w pr #93

2021-03-12 19:33 UTC, KrolMateusz commented on src/presentation/rest/FormController.ts
> +    }
Można przenieść do pliku `VolunteerSubmissionsController.ts`

2021-03-12 19:33 UTC, KrolMateusz commented on src/application/FormService.ts
> +    }
Można przenieść do pliku `VolunteerSubmissionsService.ts`

2021-03-13 13:53 UTC, KrolMateusz submitted a review, later dismissed

2021-03-13 15:50 UTC, bat098 approved these changes, later dismissed

2021-03-13 16:21 UTC, KrolMateusz approved these changes

2021-03-13 16:24 UTC, bat098 approved these changes

2021-03-13 16:48 UTC, merged